### PR TITLE
started support for bootstrap 5

### PR DESCRIPTION
**Pull request by elwingert**
The two iniitial changes I noticed
the file class needs to be only form-control and not form-control-file
the label class needs to be form-label and not control label

### CODE REVIEW

**Comment by xkpx64** [comment]
Awesome work keep it up mate

**Comment by xkpx64** [comment]
As my understanding goes we need to change the wrapper a little bit to support the new features.
Lets hope we got full bootstrap 5 update soon
### Floating Labels
Changed:
`<div class="form-group"--> form-floating`

Added `<label for="floatingInputValue">Input with value</label>`
```
<form class="form-floating">
  <input type="email" class="form-control" id="floatingInputValue" placeholder="name@example.com" value="test@example.com">
  <label for="floatingInputValue">Input with value</label>
</form>```

**Comment by xkpx64** [comment]
For alerts ->  data-dismiss="alert" changed to  data-bs-dismiss="alert"
Almost anything data-releated now is data-bs-something
And class changed from `close` to `btn-close`

This works for me taken from bs5-documentation and implemented , and move it before closing the div. [ [https://getbootstrap.com/docs/5.0/components/alerts/](url) ]
`$return .= "<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n";`
Also add this to `alert-error` in bootstrap wrapper `alert-dismissible`, also you can add `fade` + `show` for effects
Result:
Capture

**Comment by elwingert** [comment]
> As my understanding goes we need to change the wrapper a little bit to support the new features.
> Lets hope we got full bootstrap 5 update soon
> ### Floating Labels
> 
> Changed:
> `<div class="form-group"--> form-floating`
> 
> Added `<label for="floatingInputValue">Input with value</label>`
> 
> ```
> <form class="form-floating">
>   <input type="email" class="form-control" id="floatingInputValue" placeholder="name@example.com" value="test@example.com">
>   <label for="floatingInputValue">Input with value</label>
> </form>```
> ```

I missed the floating forms, that is very cool!  I'm not sure how exactly how @timgavin would want to implement those, maybe an optional parameter (customization) to either build a regular form or a floating form.

**Comment by xkpx64** [comment]
Additional : -- according to this https://getbootstrap.com/docs/5.0/migration/
`form-control-file` is removed
Renamed `sr-only` and `sr-only-focusable` to `visually-hidden` and `visually-hidden-focusable`

**Comment by timgavin** [comment]
@elwingert thank you for starting this! I took a quick look at the code and it looks like you're replacing the current Bootstrap 4 wrapper with 5; is that correct? If so, I can't accept this pr as Formr needs to support BS 3, 4, and 5... 5 needs its own wrapper methods independent of 3 and 4.

**Comment by elwingert** [comment]
Hey @timgavin, I attempted to make bootstrap 5 the default, while creating a new wrapper of bootstrap4 for backwards compatibilty.  I could certainly have missed something in doing so.  If so, I can either make the adjustment or feel free to close this pull request as well.  Thanks, this library is a pleasure to use!

**Comment by timgavin** [comment]
I'm closing this as I've started adding support for Bootstrap 5 in v1.3.7, in which I've also attempted to simplify the process of creating wrappers... old way was too confusing!

Thanks again for your support!

**Comment by elwingert** [comment]
Great, thanks @timgavin !

**Pull request closed without merging**
